version: "3"

services:
  web:
    build:
      context: .
      dockerfile: deploy/Dockerfile
    ports:
      - "3005:80"
    volumes:
      - "./:/app"
    command: "php -S 0.0.0.0:80 -t public"

  gotenberg:
    image: gotenberg/gotenberg:7
    ports:
      - "3000:3000"
    # important, as gotenberg require significant memories. see:
    # - https://github.com/gotenberg/gotenberg/issues/465#issuecomment-1146075750
    # - https://docs.docker.com/compose/compose-file/deploy/#resources
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: 500M
        reservations:
          cpus: '0.50'
          memory: 200M
